# Generated by Django 2.2.10 on 2020-02-25 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='pdf_copy',
        ),
        migrations.AddField(
            model_name='service',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Rate'),
        ),
    ]
