# Generated by Django 2.2.10 on 2020-02-26 08:38

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('condominium', '0004_auto_20200218_0813'),
        ('payments', '0002_auto_20200225_1620'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meter_type', models.CharField(choices=[('EM', 'Energy meter')], default='EM', max_length=2, verbose_name='Meter type')),
                ('serial_number', models.CharField(max_length=64, unique=True, verbose_name='Serial number')),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='condominium.Apartment', verbose_name='Apartment')),
            ],
            options={
                'verbose_name': 'Meter',
                'verbose_name_plural': 'Meters',
            },
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='type',
            new_name='payment_type',
        ),
        migrations.AddField(
            model_name='service',
            name='uom',
            field=models.CharField(default='sq.m.', max_length=8, verbose_name='Default units of measurement'),
        ),
        migrations.AddField(
            model_name='service',
            name='uom_type',
            field=models.CharField(choices=[('BA', 'By square metre'), ('BC', 'By counter')], default='BA', max_length=2, verbose_name='Measurement type'),
        ),
        migrations.CreateModel(
            name='MeterRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Value')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payments.Meter', verbose_name='Meter')),
            ],
            options={
                'verbose_name': 'Meter',
                'verbose_name_plural': 'Meters',
            },
        ),
    ]
