# Generated by Django 2.2.10 on 2020-02-27 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('condominium', '0005_auto_20200226_1524'),
        ('payments', '0004_auto_20200226_1524'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Payment value')),
            ],
        ),
        migrations.RemoveField(
            model_name='payment',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='bill',
        ),
        migrations.AddField(
            model_name='payment',
            name='apartment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='condominium.Apartment', verbose_name='Apartment'),
        ),
        migrations.AddField(
            model_name='payment',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Payment value'),
        ),
        migrations.AddField(
            model_name='service',
            name='house',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='condominium.House', verbose_name='House'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterUniqueTogether(
            name='service',
            unique_together={('house', 'name')},
        ),
        migrations.DeleteModel(
            name='BillPayment',
        ),
        migrations.AddField(
            model_name='paymentservice',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payments.Payment', verbose_name='Payment'),
        ),
        migrations.AddField(
            model_name='paymentservice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payments.Service', verbose_name='Service'),
        ),
        migrations.AddField(
            model_name='payment',
            name='service',
            field=models.ManyToManyField(blank=True, through='payments.PaymentService', to='payments.Service', verbose_name='Services'),
        ),
    ]
