# Generated by Django 2.2.10 on 2020-02-27 09:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0005_auto_20200227_0916'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AddField(
            model_name='bill',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Date updated'),
        ),
    ]
