# Generated by Django 2.2.10 on 2020-02-28 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_auto_20200227_0955'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='date',
            new_name='period',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='date_updated',
        ),
        migrations.AlterField(
            model_name='payment',
            name='date_created',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Date updated'),
        ),
    ]
