# Generated by Django 2.2.10 on 2020-04-10 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_auto_20200301_1707'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='action',
        ),
        migrations.AddField(
            model_name='payment',
            name='liqpay_responce',
            field=models.TextField(blank=True, null=True, verbose_name='LiqPay responce'),
        ),
    ]
