# Generated by Django 3.0.7 on 2020-06-11 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_auto_20200410_0916'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='service',
            field=models.ManyToManyField(blank=True, through='payments.BillLine', to='payments.Service', verbose_name='Services'),
        ),
    ]
