# Generated by Django 3.0.7 on 2020-06-15 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('condominium', '0006_auto_20200302_0543'),
        ('payments', '0010_bill_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Name'),
        ),
        migrations.AlterUniqueTogether(
            name='service',
            unique_together=set(),
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Rate')),
                ('from_date', models.DateField(verbose_name='Actual from')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='condominium.House', verbose_name='House')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.Service', verbose_name='Service')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'unique_together': {('service', 'house')},
            },
        ),
        migrations.RemoveField(
            model_name='service',
            name='house',
        ),
        migrations.RemoveField(
            model_name='service',
            name='rate',
        ),
        migrations.AddField(
            model_name='service',
            name='houses',
            field=models.ManyToManyField(through='payments.Rate', to='condominium.House', verbose_name='Houses'),
        ),
    ]
