# Generated by Django 3.0.7 on 2020-06-24 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0011_auto_20200615_1049'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meterrecord',
            options={'verbose_name': 'MeterRecord', 'verbose_name_plural': 'MeterRecords'},
        ),
        migrations.AlterModelOptions(
            name='rate',
            options={'verbose_name': 'Rate', 'verbose_name_plural': 'Rates'},
        ),
        migrations.RenameField(
            model_name='rate',
            old_name='rate',
            new_name='value',
        ),
    ]
