# Generated by Django 3.0.7 on 2020-07-09 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0012_auto_20200624_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='exemption_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Exemption value'),
        ),
    ]
