# Generated by Django 3.0.7 on 2020-07-15 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0013_bill_exemption_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='exemption_value',
        ),
        migrations.AddField(
            model_name='billline',
            name='exemption_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Exemption value'),
        ),
    ]
