version: '3.8'
services:
###########
# BACKEND #
###########
  appart-back:
    build: .
    image: &img appart_back:latest
    command: ['gunicorn', '--bind', '0.0.0.0:8000', 'appart.wsgi:application',
              '--worker-tmp-dir', '/dev/shm', '--workers', '2',
              '--threads', '4', '--worker-class', 'gthread']
    network_mode: host
    # volumes:
    #   - back_data:/home/app
    env_file:
      - ./.env.prod
    entrypoint: ['/home/app/entrypoint.sh']
############
# FRONTEND #
############
  appart-front:
    build:
      context: ./appart-frontend
    image: appart_front:latest
    command: [nginx, '-g', 'daemon off;']
    ports:
      - 8002:8080
    # volumes:
    #   - front_data:/usr/share/nginx/html
    depends_on:
      - appart-back
##########
# CELERY #
##########
  celery:
    # build: .
    image: *img
    command: ['celery', '-A', 'appart', 'worker', '-l', 'info']
    network_mode: host
    env_file:
      - ./.env.prod
###############
# CELERY BEAT #
###############
  celery-beat:
    image: *img
    command: ['celery', '-A', 'appart', 'beat', '-l', 'info']
    network_mode: host
    env_file:
      - ./.env.prod

# volumes:
#   front_data:
#   back_data:
