""" Business logic for payments app """

from payments.models import Bill


def bill_number_generate(apartment, bill_date):
    """ return autogenerated bill number in format %Y%m%d-N """
    today_orders_count = Bill.objects.filter(date_created__contains=bill_date) \
                                     .count() + 1
    return f'{bill_date}-{apartment.deal_number}-{today_orders_count}'


def debt_for_service(apartment, service, date):          # TODO
    """ return previous debt of apartment for service """

    return 0

def debt_for_month(apartment, service):
    """ return previous debt of apartment for service """

    return apartment.area * service.rate


def total_debt(apartment):          # TODO
    """ return previous debt of apartment for service """

    return 0
