# Generated by Django 2.2.10 on 2020-03-11 09:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dimservice', '0002_work_duration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='work',
            old_name='active',
            new_name='is_active',
        ),
        migrations.AddField(
            model_name='order',
            name='number',
            field=models.CharField(default=django.utils.timezone.now, max_length=32, unique=True, verbose_name='Order number'),
            preserve_default=False,
        ),
    ]
