# Generated by Django 2.2.10 on 2020-04-08 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dimservice', '0003_auto_20200311_0937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='number',
        ),
    ]
