# Generated by Django 2.2.10 on 2020-05-15 12:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dimservice', '0006_auto_20200513_1743'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='execution',
            options={'verbose_name': 'Execution', 'verbose_name_plural': 'Executions'},
        ),
        migrations.AlterField(
            model_name='work',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(seconds=3600), verbose_name='Duration'),
        ),
    ]
