# Generated by Django 2.2.7 on 2019-11-07 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='theme',
            field=models.CharField(choices=[('LT', 'Light'), ('DK', 'Dark')], default='LT', max_length=2, verbose_name='Theme'),
        ),
    ]
