# Generated by Django 2.2.7 on 2019-11-07 16:18

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20191107_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='avatars/no_image.jpg', upload_to=accounts.models.avatar_directory_path, verbose_name='Photo'),
        ),
    ]
