# Generated by Django 2.2.10 on 2020-04-16 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200327_1310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='theme',
        ),
        migrations.AddField(
            model_name='user',
            name='is_registered',
            field=models.BooleanField(default=False, verbose_name='Is registered'),
        ),
    ]
