# Generated by Django 2.2.10 on 2020-04-16 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200416_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_registered',
            field=models.BooleanField(default=False, verbose_name='Registered'),
        ),
    ]
