# Generated by Django 2.2.10 on 2020-05-19 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20200416_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='lang',
            field=models.CharField(choices=[('EN', 'English'), ('UA', 'Ukrainian')], default='UA', max_length=2, verbose_name='Interface language'),
        ),
    ]
