# Generated by Django 2.2.10 on 2020-05-19 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_lang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='lang',
            field=models.CharField(choices=[('en', 'en_us'), ('uk', 'uk')], default='uk', max_length=2, verbose_name='Interface language'),
        ),
    ]
