# Generated by Django 2.2.7 on 2019-11-07 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, verbose_name='Name')),
                ('fullname', models.CharField(max_length=255, verbose_name='Full name')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Legal address')),
                ('requisites', models.CharField(blank=True, max_length=255, verbose_name='Requisites')),
                ('bank_requisites', models.CharField(blank=True, max_length=255, verbose_name='Bank details')),
                ('chief', models.CharField(blank=True, max_length=45, verbose_name='Chief')),
                ('phone', models.CharField(blank=True, max_length=13, verbose_name='Phone')),
                ('logo', models.ImageField(default='company/no_image.jpg', upload_to='company/logo/', verbose_name='Logo')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Address')),
                ('logo', models.ImageField(default='company/no_image.jpg', upload_to='company/pictures/', verbose_name='Photo')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='condominium.Company', verbose_name='Company')),
            ],
            options={
                'verbose_name': 'House',
                'verbose_name_plural': 'Houses',
                'ordering': ['-name'],
                'unique_together': {('company', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(verbose_name='House')),
                ('area', models.PositiveSmallIntegerField(blank=True, verbose_name='Area')),
                ('residents_count', models.PositiveSmallIntegerField(blank=True, verbose_name='Residents count')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='condominium.House', verbose_name='House')),
            ],
            options={
                'verbose_name': 'Apartment',
                'verbose_name_plural': 'Apartments',
                'ordering': ['-number'],
                'unique_together': {('house', 'number')},
            },
        ),
    ]
