# Generated by Django 2.2.8 on 2019-12-19 12:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=45, verbose_name='Name')),
                ('fullname', models.CharField(blank=True, max_length=255, verbose_name='Full name')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Legal address')),
                ('requisites', models.CharField(blank=True, max_length=255, verbose_name='Requisites')),
                ('bank_requisites', models.CharField(blank=True, max_length=255, verbose_name='Bank details')),
                ('chief', models.CharField(blank=True, max_length=45, verbose_name='Chief')),
                ('phone', models.CharField(blank=True, max_length=13, verbose_name='Phone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email address')),
                ('official_site', models.URLField(blank=True, verbose_name='Official site')),
                ('logo', models.ImageField(blank=True, default='company/no_image.jpg', upload_to='company/logo/', verbose_name='Logo')),
                ('photo', models.ImageField(blank=True, default='company/no_image.jpg', upload_to='company/photo/', verbose_name='Photo')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('service_numbers', models.TextField(blank=True, verbose_name='Service numbers')),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Address')),
                ('logo', models.ImageField(blank=True, default='company/no_image.jpg', upload_to='company/pictures/', verbose_name='Photo')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('apartments_count', models.PositiveSmallIntegerField(verbose_name='Apartments count')),
            ],
            options={
                'verbose_name': 'House',
                'verbose_name_plural': 'Houses',
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(verbose_name='Apartment Number')),
                ('deal_number', models.CharField(blank=True, max_length=30, verbose_name='Deal number')),
                ('area', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Area')),
                ('residents_count', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Residents count')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='condominium.House', verbose_name='House')),
                ('resident', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Resident')),
            ],
            options={
                'verbose_name': 'Apartment',
                'verbose_name_plural': 'Apartments',
                'ordering': ['house', 'number'],
                'unique_together': {('house', 'number')},
            },
        ),
    ]
