# Generated by Django 2.2.7 on 2019-11-07 16:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('condominium', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='resident',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Resident'),
        ),
    ]
