# Generated by Django 3.0 on 2019-12-09 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominium', '0002_auto_20191202_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email address'),
        ),
        migrations.AddField(
            model_name='company',
            name='official_site',
            field=models.URLField(blank=True, verbose_name='Official site'),
        ),
        migrations.AddField(
            model_name='company',
            name='photo',
            field=models.ImageField(blank=True, default='company/no_image.jpg', upload_to='company/photo/', verbose_name='Photo'),
        ),
        migrations.AddField(
            model_name='company',
            name='service_numbers',
            field=models.TextField(blank=True, verbose_name='Service numbers'),
        ),
    ]
