# Generated by Django 2.2.10 on 2020-02-17 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominium', '0002_auto_20200206_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='debt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Total debt'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is active'),
        ),
    ]
