# Generated by Django 3.0 on 2019-12-09 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominium', '0003_auto_20191209_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='deal_number',
            field=models.CharField(blank=True, max_length=30, verbose_name='Deal number'),
        ),
    ]
