# Generated by Django 2.2.7 on 2019-11-14 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominium', '0003_auto_20191113_0731'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='apartments_count',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Apartments count'),
        ),
    ]
