# Generated by Django 2.2.7 on 2019-11-20 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominium', '0004_house_apartments_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Name'),
        ),
        migrations.AlterUniqueTogether(
            name='house',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='house',
            name='company',
        ),
    ]
