# Generated by Django 2.2.10 on 2020-02-26 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominium', '0004_auto_20200218_0813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Is active'),
        ),
    ]
