# Generated by Django 2.2.7 on 2019-11-20 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominium', '0005_auto_20191120_0610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='apartments_count',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Apartments count'),
            preserve_default=False,
        ),
    ]
