# Generated by Django 2.2.7 on 2019-11-20 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominium', '0006_auto_20191120_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='area',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Area'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='residents_count',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Residents count'),
        ),
    ]
