# Generated by Django 3.0.7 on 2020-07-09 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominium', '0007_company_service_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='exemption_count',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Exemptions count'),
        ),
    ]
