# Generated by Django 2.2.7 on 2019-11-22 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominium', '0007_auto_20191120_0924'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apartment',
            options={'ordering': ['house', 'number'], 'verbose_name': 'Apartment', 'verbose_name_plural': 'Apartments'},
        ),
        migrations.AlterField(
            model_name='company',
            name='fullname',
            field=models.CharField(blank=True, max_length=255, verbose_name='Full name'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(blank=True, max_length=45, verbose_name='Name'),
        ),
    ]
