# Generated by Django 3.0.7 on 2020-07-09 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('condominium', '0008_apartment_exemption_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='area',
        ),
    ]
