# Generated by Django 2.2.7 on 2019-11-22 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominium', '0008_auto_20191122_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, default='company/no_image.jpg', upload_to='company/logo/', verbose_name='Logo'),
        ),
    ]
