# Generated by Django 2.2.7 on 2019-11-22 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominium', '0009_auto_20191122_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='logo',
            field=models.ImageField(blank=True, default='company/no_image.jpg', upload_to='company/pictures/', verbose_name='Photo'),
        ),
    ]
