# Generated by Django 3.0.7 on 2020-07-13 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominium', '0010_apartment_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='area',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Area'),
        ),
    ]
