# Generated by Django 3.0.7 on 2020-07-15 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominium', '0011_auto_20200713_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='account_number',
            field=models.CharField(max_length=30, verbose_name='Account number'),
        ),
    ]
