# Generated by Django 3.0.7 on 2020-07-18 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('condominium', '0012_auto_20200715_1550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='apartments_count',
        ),
    ]
