# Generated by Django 3.0.7 on 2020-07-30 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominium', '0014_house_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='account_number',
            field=models.CharField(max_length=30, unique=True, verbose_name='Account number'),
        ),
    ]
