# Generated by Django 2.2.7 on 2019-12-09 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='notice_status',
            field=models.CharField(choices=[('WA', 'Company'), ('IN', 'House')], default='IN', max_length=2, verbose_name='Notice status'),
        ),
    ]
