# Generated by Django 2.2.10 on 2020-04-17 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='title',
            field=models.CharField(default='Question 1', max_length=100, verbose_name='Question title'),
            preserve_default=False,
        ),
    ]
