# Generated by Django 2.2.10 on 2020-04-17 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0002_question_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='apartment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='condominium.Apartment', verbose_name='Apartment'),
        ),
    ]
