# Generated by Django 2.2.8 on 2019-12-13 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0003_auto_20191210_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='notice_type',
            field=models.CharField(choices=[('CO', 'About company'), ('HO', 'About house'), ('AP', 'About apartment')], default='HO', max_length=2, verbose_name='Notice type'),
        ),
    ]
