# Generated by Django 2.2.8 on 2019-12-16 19:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0004_auto_20191213_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='notice_status',
            field=models.CharField(choices=[('WA', 'Warning'), ('IN', 'Info')], default='IN', max_length=2, verbose_name='News status'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='notice_type',
            field=models.CharField(choices=[('CO', 'About company'), ('HO', 'About house'), ('AP', 'About apartment')], default='HO', max_length=2, verbose_name='News type'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='text',
            field=models.TextField(verbose_name='News text'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='title',
            field=models.CharField(max_length=100, verbose_name='News title'),
        ),
        migrations.AlterField(
            model_name='question',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
    ]
