# Generated by Django 2.2.8 on 2019-12-18 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0006_auto_20191218_1155'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-news_status', '-date_created'], 'verbose_name': 'News'},
        ),
        migrations.RenameField(
            model_name='news',
            old_name='notice_status',
            new_name='news_status',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='notice_type',
            new_name='news_type',
        ),
    ]
