# Generated by Django 2.2.8 on 2019-12-18 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominium', '0004_apartment_deal_number'),
        ('notice', '0007_auto_20191218_1220'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-date_created'], 'verbose_name': 'News'},
        ),
        migrations.RemoveField(
            model_name='news',
            name='house',
        ),
        migrations.RemoveField(
            model_name='news',
            name='news_type',
        ),
        migrations.AddField(
            model_name='news',
            name='houses',
            field=models.ManyToManyField(blank=True, to='condominium.House', verbose_name='Houses'),
        ),
    ]
