# Generated by Django 2.2.8 on 2019-12-18 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0008_auto_20191218_1358'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-news_status', '-date_created'], 'verbose_name': 'News'},
        ),
    ]
