name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Backend Docker image
      run: docker build . --file Dockerfile --tag kozlyuk/dimonline:appart-back-$(date +%s) && docker push kozlyuk/dimonline:appart-back-$(date +%s)

    - uses: actions/checkout@v2
    - name: Build the Frontend Docker image
      run: docker build . --file appart-frontend/Dockerfile --tag appart-front:$(date +%s) && docker push kozlyuk/dimonline:appart-front-$(date +%s)

